# ---------------------------------------------------------------------------
# LakeVolume.py
# Created on: 2010-12-14 08:29:07.00000
#   (generated by ArcGIS/ModelBuilder)
# Usage: LakeVolume <Input_Shorelines> <Input_Depth_Points> <Output_Lakes> <Output_Surface> 
# Description: 
# Calculates the volume of a set of lakes based on depth samples (points) within the polygon defined by the shoreline.
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy

# Check out any necessary licenses
arcpy.CheckOutExtension("3D")

# Script arguments
Input_Shorelines = arcpy.GetParameterAsText(0)

Input_Depth_Points = arcpy.GetParameterAsText(1)

Output_Lakes = arcpy.GetParameterAsText(2)

Output_Surface = arcpy.GetParameterAsText(3)

# Local variables:
Output_Lakes__temp_ = Output_Surface
Output_Lakes__temp2_ = Output_Lakes__temp_
Output_Layer = Input_Shorelines
Output_Layer_Name = Output_Layer
Output_with_depth = Output_Layer_Name
Output_with_depth_2 = Output_with_depth
Output_Dataset = Input_Depth_Points

# Process: Merge
arcpy.Merge_management(Input_Depth_Points, Output_Dataset, "")

# Process: Make Feature Layer
arcpy.MakeFeatureLayer_management(Input_Shorelines, Output_Layer, "", "", "FID FID VISIBLE NONE;Shape Shape VISIBLE NONE;OBJECTID OBJECTID VISIBLE NONE;SHAPE_Leng SHAPE_Leng VISIBLE NONE;SHAPE_Area SHAPE_Area VISIBLE NONE;PONDNAME PONDNAME VISIBLE NONE")

# Process: Select Layer By Location
arcpy.SelectLayerByLocation_management(Output_Layer, "INTERSECT", Output_Dataset, "", "NEW_SELECTION")

# Process: Add Field
arcpy.AddField_management(Output_Layer_Name, "xx_depth", "DOUBLE", "", "", "", "", "NON_NULLABLE", "NON_REQUIRED", "")

# Process: Calculate Field
arcpy.CalculateField_management(Output_with_depth, "xx_depth", "0", "VB", "")

# Process: Create TIN
arcpy.CreateTin_3d(Output_Surface, "", "# Depth masspoints <None>;DENA_SamplingLakes_Digitized xx_depth hardclip <None>", "DELAUNAY")

# Process: Polygon Volume (2)
arcpy.PolygonVolume_3d(Output_Surface, Output_with_depth_2, "xx_depth", "ABOVE", "Volume", "SArea", "0")

# Process: Delete Field
arcpy.DeleteField_management(Output_Lakes__temp_, "xx_depth")

# Process: Copy Features
arcpy.CopyFeatures_management(Output_Lakes__temp2_, Output_Lakes, "", "0", "0", "0")

