# ---------------------------------------------------------------------------
# SquareBuilding.py
# Created on: 2011-01-26 14:59:52.00000
#   (generated by ArcGIS/ModelBuilder)
# Usage: SquareBuilding <Building_Edges> <Building_Polygons> 
# Description: 
# Create rectangular buildings from one edge.  Assumes the NPS Alaska building edge data collection schema
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy

# Load required toolboxes
arcpy.ImportToolbox("C:/Users/resarwas/Documents/Visual Studio 2010/Projects/AlaskaPak/Scripts/Alaska Pak Development.tbx")

# Script arguments
Building_Edges = arcpy.GetParameterAsText(0)

Building_Polygons = arcpy.GetParameterAsText(1)

# Local variables:
edges = Building_Edges
edges__2_ = edges
edges__3_ = edges__2_
Building_Polygons__2_ = Building_Polygons

# Process: Copy Features
arcpy.CopyFeatures_management(Building_Edges, edges, "", "0", "0", "0")

# Process: Add Field
arcpy.AddField_management(edges, "zz_offset", "DOUBLE", "", "", "", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Calculate Field
arcpy.CalculateField_management(edges__2_, "zz_offset",
                                "!Width_Ft! * 0.3048 * (1 if !Right_Left!.lower()[0] == 'r' else -1)", "PYTHON", "")

# Process: Line to Rectangle
arcpy.Line2Rect_AlaskaPak(edges__3_, "zz_offset", Building_Polygons)

# Process: Delete Field
arcpy.DeleteField_management(Building_Polygons, "zz_offset")