# ---------------------------------------------------------------------------
# Point2Poly.py
# Created on: 2011-01-26 16:13:49.00000
#   (generated by ArcGIS/ModelBuilder)
# Usage: Point2Poly <Point_Features> <Polygon_Features> <Polygon_Id_Field> <Sort_Field> 
# Description: 
# Takes an ordered set of points and converts them to a set of polygons
# ---------------------------------------------------------------------------

# Set the necessary product code
# import arcinfo


# Import arcpy module
import arcpy

# Script arguments
Point_Features = arcpy.GetParameterAsText(0)

Polygon_Features = arcpy.GetParameterAsText(1)

Polygon_Id_Field = arcpy.GetParameterAsText(2)

Sort_Field = arcpy.GetParameterAsText(3)

# Local variables:
lines = Point_Features

# Process: Points To Line
arcpy.PointsToLine_management(Point_Features, lines, Polygon_Id_Field, Sort_Field, "CLOSE")

# Process: Feature To Polygon
arcpy.FeatureToPolygon_management("in_memory\\lines", Polygon_Features, "", "ATTRIBUTES", "")

